"""Write one prompt file per review and per grading, with labels that hide the arm.

    make_jobs.py <run-dir> <phase> <arm>:<runs> [<arm>:<runs> ...]

Arms: a map variant directory name under each case (`map-full`, `map-core3`, or any
later `map-<name>`), or `source`. Writes, under <run-dir>/<phase>/:

    jobs/<case>.<label>.md     a reviewer's full prompt; it writes reviews/<case>.<label>.md
    grade/<case>.md            the grader's full prompt; it writes grades/<case>.json
    mapping.json               label → arm, for aggregation only (graders never see it)
    agents.txt                 the one-line prompt to hand each agent, one per line
"""
import json, pathlib, random, sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[3]
PROMPTS = HERE.parent / "prompts"
AREAS = {
    "A1": "the Settings window — general settings, accounts, the account editor",
    "A2": "the main window shell — window controller, split view, sidebar, editor area, title",
    "A3": "the session tab — the new-session view, the composer, and the tab's binder",
    "A4": "the transcript page and the documents shown beside it",
}


def material(arm: str, case_dir: pathlib.Path) -> str:
    if arm == "source":
        return (f"The sources under review: `{case_dir}/src/macos/` — the app is `ccterm/`, its views are in "
                "`Components/Sources/Components/` and the values they show in `Components/Sources/DisplayModels/`. "
                "Search and read what you need.")
    d = case_dir / arm
    if arm.endswith("-v2") and (d / "units").exists():
        # Read in levels: the top first, a unit only where the upper levels point.
        return (f"The structure map of the sources under review, in `{d}/` — nothing else. It was generated by "
                "`make arch` from those sources; you may not read the sources themselves. Read it in levels: "
                "`index.md` first (the top of the component tree, with counts of what each region holds), then "
                "`tree.md`, `data.md` and `rules.md`. Open a unit file under `units/` only to verify a suspicion "
                "in the area — `units/index.md` lists them and explains their labels.")
    text = (f"The structure map of the sources under review, in `{d}/` — nothing else. It was generated by "
            "`make arch` from those sources; you may not read the sources themselves. Start with `index.md`, then "
            "`tree.md`, `data.md` and `rules.md`")
    if (d / "units").exists():
        text += ("; `units/index.md` explains the labels the unit files use — read it, then the unit files "
                 "that cover the area")
    return text + "."


def main() -> None:
    run, phase, *arms = sys.argv[1:]
    run = pathlib.Path(run).resolve()
    base = run / phase
    for sub in ("jobs", "reviews", "grade", "grades"):
        (base / sub).mkdir(parents=True, exist_ok=True)
    reviewer = (PROMPTS / "reviewer.md").read_text()
    grader = (PROMPTS / "grader.md").read_text()
    rng = random.Random(f"{run.name}/{phase}")
    mapping, lines = {}, []
    plan = [(a.split(":")[0], int(a.split(":")[1])) for a in arms]
    for case_dir in sorted(p for p in run.iterdir() if (p / "src").exists()):
        case = case_dir.name
        slots = [arm for arm, n in plan for _ in range(n)]
        labels = rng.sample(range(100, 1000), len(slots))
        reviews = []
        for arm, label in zip(slots, labels):
            lab = f"r{label}"
            mapping[f"{case}.{lab}"] = arm
            out = base / "reviews" / f"{case}.{lab}.md"
            area = json.loads((case_dir / "key.json").read_text())["area"]
            prompt = (reviewer.replace("{AREA}", AREAS[area]).replace("{MATERIAL}", material(arm, case_dir))
                      .replace("{REPO}", str(REPO)))
            prompt += f"\n\nWrite your output to `{out}` and reply only \"done\".\n"
            job = base / "jobs" / f"{case}.{lab}.md"
            job.write_text(prompt)
            lines.append(f"Read {job} and do exactly what it says.")
            reviews.append(f"`{out}` (label {lab})")
        g = (grader.replace("{CASE}", str(case_dir)).replace("{SRC}", str(case_dir / "src/macos"))
             .replace("{REVIEWS}", "; ".join(reviews)).replace("{REPO}", str(REPO))
             .replace("{OUT}", str(base / "grades" / f"{case}.json")))
        (base / "grade" / f"{case}.md").write_text(g)
    (base / "mapping.json").write_text(json.dumps(mapping, indent=2))
    (base / "agents.txt").write_text("\n".join(lines) + "\n")
    print(f"{len(lines)} review jobs, {len(list((base / 'grade').iterdir()))} grade jobs in {base}")


if __name__ == "__main__":
    main()
