import Testing
@testable import AgentSDK

// MARK: - LocalCommandCaveatXML Tests

@Suite struct LocalCommandCaveatXMLTests {
    @Test func parsesCaveat() {
        let xml = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"
        let result = LocalCommandCaveatXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.caveat.contains("Caveat") == true)
    }

    @Test func failsWithoutCaveat() {
        let xml = "<command-name>/clear</command-name>"
        let result = LocalCommandCaveatXML(xmlString: xml)
        #expect(result == nil)
    }
}

// MARK: - SlashCommandXML Tests

@Suite struct SlashCommandXMLTests {
    @Test func parsesFullSlashCommand() {
        let xml = """
        <command-name>/clear</command-name>
        <command-message>clear</command-message>
        <command-args>--all</command-args>
        """
        let result = SlashCommandXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.commandName == "/clear")
        #expect(result?.commandMessage == "clear")
        #expect(result?.commandArgs == "--all")
    }

    @Test func parsesMinimalSlashCommand() {
        let xml = "<command-name>/help</command-name>"
        let result = SlashCommandXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.commandName == "/help")
        #expect(result?.commandMessage == nil)
        #expect(result?.commandArgs == nil)
    }

    @Test func failsWithoutCommandName() {
        let xml = "<command-message>clear</command-message>"
        let result = SlashCommandXML(xmlString: xml)
        #expect(result == nil)
    }
}

// MARK: - LocalCommandOutputXML Tests

@Suite struct LocalCommandOutputXMLTests {
    @Test func parsesStdout() {
        let xml = "<local-command-stdout>(no content)</local-command-stdout>"
        let result = LocalCommandOutputXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.stdout == "(no content)")
        #expect(result?.stderr == nil)
    }

    @Test func parsesStderr() {
        let xml = "<local-command-stderr>error output</local-command-stderr>"
        let result = LocalCommandOutputXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.stdout == nil)
        #expect(result?.stderr == "error output")
    }

    @Test func parsesBoth() {
        let xml = "<local-command-stdout>out</local-command-stdout><local-command-stderr>err</local-command-stderr>"
        let result = LocalCommandOutputXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.stdout == "out")
        #expect(result?.stderr == "err")
    }
}

// MARK: - TaskNotificationXML Tests

@Suite struct TaskNotificationXMLTests {
    @Test func parsesFullTaskNotification() {
        let xml = """
        <task-notification>
        <task-id>a95fcfa15a958f619</task-id>
        <tool-use-id>toolu_01XokUVZDcfD3cdRXcJBbQdg</tool-use-id>
        <output-file>/private/tmp/tasks/a95fcfa15a958f619.output</output-file>
        <status>completed</status>
        <summary>Agent "Refine height estimation" completed</summary>
        <result>The code is clean</result>
        <usage><total_tokens>43540</total_tokens><tool_uses>17</tool_uses><duration_ms>121803</duration_ms></usage>
        <worktree><worktreePath>/Users/test/worktrees/agent-xxx</worktreePath><worktreeBranch>worktree-agent-xxx</worktreeBranch></worktree>
        </task-notification>
        Full transcript available at: /private/tmp/transcript
        """
        let result = TaskNotificationXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.taskId == "a95fcfa15a958f619")
        #expect(result?.toolUseId == "toolu_01XokUVZDcfD3cdRXcJBbQdg")
        #expect(result?.status == "completed")
        #expect(result?.summary == "Agent \"Refine height estimation\" completed")
        #expect(result?.result == "The code is clean")
        #expect(result?.usage?.totalTokens == "43540")
        #expect(result?.usage?.toolUses == "17")
        #expect(result?.usage?.durationMs == "121803")
        #expect(result?.worktree?.path == "/Users/test/worktrees/agent-xxx")
        #expect(result?.worktree?.branch == "worktree-agent-xxx")
    }

    @Test func parsesMinimalTaskNotification() {
        let xml = """
        <task-notification>
        <task-id>abc123</task-id>
        <status>completed</status>
        <summary>Done</summary>
        </task-notification>
        """
        let result = TaskNotificationXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.taskId == "abc123")
        #expect(result?.toolUseId == nil)
        #expect(result?.outputFile == nil)
        #expect(result?.result == nil)
        #expect(result?.usage == nil)
        #expect(result?.worktree == nil)
    }

    @Test func failsWithoutRoot() {
        let xml = "<task-id>abc</task-id><status>ok</status><summary>s</summary>"
        let result = TaskNotificationXML(xmlString: xml)
        #expect(result == nil)
    }
}

// MARK: - BashInputXML Tests

@Suite struct BashInputXMLTests {
    @Test func parsesBashInput() {
        let xml = "<bash-input>gst</bash-input>"
        let result = BashInputXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.input == "gst")
    }

    @Test func failsWithoutInput() {
        let xml = "<bash-stdout>output</bash-stdout>"
        let result = BashInputXML(xmlString: xml)
        #expect(result == nil)
    }
}

// MARK: - BashOutputXML Tests

@Suite struct BashOutputXMLTests {
    @Test func parsesBashOutput() {
        let xml = "<bash-stdout>On branch main</bash-stdout><bash-stderr></bash-stderr>"
        let result = BashOutputXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.stdout == "On branch main")
        #expect(result?.stderr == "")
    }

    @Test func parsesStdoutOnly() {
        let xml = "<bash-stdout>output</bash-stdout>"
        let result = BashOutputXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.stdout == "output")
        #expect(result?.stderr == nil)
    }
}

// MARK: - TaskOutputXML Tests

@Suite struct TaskOutputXMLTests {
    @Test func parsesFullTaskOutput() {
        let xml = """
        <retrieval_status>success</retrieval_status>

        <task_id>bwbagfks4</task_id>

        <task_type>local_bash</task_type>

        <status>completed</status>

        <exit_code>0</exit_code>

        <output>some output here</output>
        """
        let result = TaskOutputXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.retrievalStatus == "success")
        #expect(result?.taskId == "bwbagfks4")
        #expect(result?.taskType == "local_bash")
        #expect(result?.status == "completed")
        #expect(result?.exitCode == "0")
        #expect(result?.output == "some output here")
    }

    @Test func parsesMinimalTaskOutput() {
        let xml = """
        <retrieval_status>success</retrieval_status>
        <task_id>abc</task_id>
        <status>completed</status>
        """
        let result = TaskOutputXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.taskType == nil)
        #expect(result?.exitCode == nil)
        #expect(result?.output == nil)
    }

    @Test func parsesTimeoutTaskOutput() {
        let xml = "<retrieval_status>timeout</retrieval_status>"
        let result = TaskOutputXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.retrievalStatus == "timeout")
        #expect(result?.taskId == nil)
        #expect(result?.status == nil)
    }
}

// MARK: - PersistedOutputXML Tests

@Suite struct PersistedOutputXMLTests {
    @Test func parsesPersistedOutput() {
        let xml = """
        <persisted-output>
        Output too large (689.3KB). Full output saved to: /Users/test/tool-results/b697qe98u.txt

        Preview (first 2KB):
        some preview content
        </persisted-output>
        """
        let result = PersistedOutputXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.content.contains("Output too large") == true)
        #expect(result?.content.contains("Preview") == true)
    }
}

// MARK: - SystemReminderXML Tests

@Suite struct SystemReminderXMLTests {
    @Test func parsesSystemReminder() {
        let xml = """
        <system-reminder>
        Called the Bash tool with the following input: {"command":"ls","description":"List files"}
        </system-reminder>
        """
        let result = SystemReminderXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.content.contains("Bash tool") == true)
    }
}

// MARK: - ToolUseErrorXML Tests

@Suite struct ToolUseErrorXMLTests {
    @Test func parsesToolUseError() {
        let xml = "<tool_use_error>File does not exist.</tool_use_error>"
        let result = ToolUseErrorXML(xmlString: xml)
        #expect(result != nil)
        #expect(result?.error == "File does not exist.")
    }
}

// MARK: - XMLContent Enum Dispatch Tests

@Suite struct XMLContentDispatchTests {
    @Test func dispatchesLocalCommandCaveat() {
        let xml = "<local-command-caveat>Caveat: Do not respond to these messages.</local-command-caveat>"
        let content = XMLContent(xmlString: xml)
        guard case .localCommandCaveat(let c) = content else {
            Issue.record("Expected localCommandCaveat case")
            return
        }
        #expect(c.caveat.contains("Caveat"))
    }

    @Test func dispatchesSlashCommand() {
        let xml = "<command-name>/clear</command-name><command-message>clear</command-message>"
        let content = XMLContent(xmlString: xml)
        guard case .slashCommand(let cmd) = content else {
            Issue.record("Expected slashCommand case")
            return
        }
        #expect(cmd.commandName == "/clear")
    }

    @Test func dispatchesSlashCommandOverCaveat() {
        // If both <command-name> and <local-command-caveat> present, slashCommand wins
        let xml = "<local-command-caveat>Caveat</local-command-caveat><command-name>/clear</command-name>"
        let content = XMLContent(xmlString: xml)
        guard case .slashCommand = content else {
            Issue.record("Expected slashCommand case (should take priority over caveat)")
            return
        }
    }

    @Test func dispatchesLocalCommandOutput() {
        let xml = "<local-command-stdout>some output</local-command-stdout>"
        let content = XMLContent(xmlString: xml)
        guard case .localCommandOutput(let o) = content else {
            Issue.record("Expected localCommandOutput case")
            return
        }
        #expect(o.stdout == "some output")
    }

    @Test func dispatchesBashInput() {
        let xml = "<bash-input>ls</bash-input>"
        let content = XMLContent(xmlString: xml)
        guard case .bashInput(let bash) = content else {
            Issue.record("Expected bashInput case")
            return
        }
        #expect(bash.input == "ls")
    }

    @Test func dispatchesBashOutput() {
        let xml = "<bash-stdout>output</bash-stdout>"
        let content = XMLContent(xmlString: xml)
        guard case .bashOutput(let bash) = content else {
            Issue.record("Expected bashOutput case")
            return
        }
        #expect(bash.stdout == "output")
    }

    @Test func dispatchesTaskNotification() {
        let xml = """
        <task-notification>
        <task-id>abc</task-id>
        <status>completed</status>
        <summary>Done</summary>
        </task-notification>
        """
        let content = XMLContent(xmlString: xml)
        guard case .taskNotification(let tn) = content else {
            Issue.record("Expected taskNotification case")
            return
        }
        #expect(tn.taskId == "abc")
    }

    @Test func dispatchesTaskOutput() {
        let xml = "<retrieval_status>success</retrieval_status><task_id>x</task_id><status>ok</status>"
        let content = XMLContent(xmlString: xml)
        guard case .taskOutput(let to) = content else {
            Issue.record("Expected taskOutput case")
            return
        }
        #expect(to.taskId == "x")
    }

    @Test func dispatchesPersistedOutput() {
        let xml = "<persisted-output>Too large</persisted-output>"
        let content = XMLContent(xmlString: xml)
        guard case .persistedOutput(let po) = content else {
            Issue.record("Expected persistedOutput case")
            return
        }
        #expect(po.content == "Too large")
    }

    @Test func dispatchesSystemReminder() {
        let xml = "<system-reminder>Some reminder</system-reminder>"
        let content = XMLContent(xmlString: xml)
        guard case .systemReminder(let sr) = content else {
            Issue.record("Expected systemReminder case")
            return
        }
        #expect(sr.content == "Some reminder")
    }

    @Test func dispatchesToolUseError() {
        let xml = "<tool_use_error>Permission denied</tool_use_error>"
        let content = XMLContent(xmlString: xml)
        guard case .toolUseError(let e) = content else {
            Issue.record("Expected toolUseError case")
            return
        }
        #expect(e.error == "Permission denied")
    }

    @Test func returnsNilForNonXml() {
        let content = XMLContent(xmlString: "Just a plain text message with no XML")
        #expect(content == nil)
    }

    @Test func returnsNilForUnknownXml() {
        let content = XMLContent(xmlString: "<unknown-tag>value</unknown-tag>")
        #expect(content == nil)
    }
}

// MARK: - Integration Extension Tests

@Suite struct XMLContentIntegrationTests {
    @Test func userMessageContentXmlContent() {
        let content = UserMessageContent.text("<command-name>/help</command-name>")
        let xml = content.xmlContent
        guard case .slashCommand(let cmd) = xml else {
            Issue.record("Expected slashCommand")
            return
        }
        #expect(cmd.commandName == "/help")
    }

    @Test func userMessageContentCaveatXmlContent() {
        let content = UserMessageContent.text("<local-command-caveat>Caveat text</local-command-caveat>")
        let xml = content.xmlContent
        guard case .localCommandCaveat(let c) = xml else {
            Issue.record("Expected localCommandCaveat")
            return
        }
        #expect(c.caveat == "Caveat text")
    }

    @Test func userMessageContentBlocksReturnsNil() {
        let content = UserMessageContent.blocks([])
        #expect(content.xmlContent == nil)
    }

    @Test func userMessageContentPlainTextReturnsNil() {
        let content = UserMessageContent.text("Hello world")
        #expect(content.xmlContent == nil)
    }

    @Test func toolResultBlockXmlContent() throws {
        let block = ToolResultBlock(toolUseId: "test", content: "<system-reminder>test</system-reminder>")
        let xml = block.xmlContent
        guard case .systemReminder(let sr) = xml else {
            Issue.record("Expected systemReminder")
            return
        }
        #expect(sr.content == "test")
    }

    @Test func toolResultBlockNonStringReturnsNil() {
        let block = ToolResultBlock(toolUseId: "test", content: nil)
        #expect(block.xmlContent == nil)
    }
}
