import Foundation

/// What a transcript records about its session besides the conversation:
/// ``Transcript/metadata``, or ``Transcript/metadata(contentsOf:)`` to read
/// only this.
public struct SessionMetadata: Sendable, Equatable {
    /// Set by the user with `/rename`.
    public var customTitle: String?
    /// Generated by the CLI.
    public var aiTitle: String?
    /// The latest prompt, flattened to one line and truncated.
    public var lastPrompt: String?
    public var tag: String?
    /// The directory the session runs in.
    public var cwd: String?
    public var gitBranch: String?
    /// How the session was started: `cli` at the CLI's prompt, `sdk-cli`
    /// through `claude -p` or an SDK, or what the launching host set in
    /// `CLAUDE_CODE_ENTRYPOINT`. `nil` in a transcript from before the CLI
    /// recorded it.
    public var entrypoint: String?
    public var createdAt: Date?
    public var updatedAt: Date?

    /// ``customTitle``, else ``aiTitle``.
    public var title: String? { customTitle ?? aiTitle }

    public init() {}
}
